//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangMayTinh
    {
        public int ID { get; set; }
        public string TenMayTinh { get; set; }
        public string HangSangXuat { get; set; }
        public Nullable<int> NamSX { get; set; }
    }
}
